### ISSUE TITLE
Compute time taken to take the survey

### ISSUE THREAD

**Issue by bateman** [micheledinanni/miniIPIP_test#86]
A timer should start when the user clicks on "Start test" on the main page and stop when they land on the "Help us improve" page. Time taken should be stored in the DB along with survey results.

**Reason**. Eliminate fake, noisy results from participants who speedrun the test by just clicking quickly and randomly on answer buttons, without even reading the statements.

**Comment by micheledinanni** [comment]
Will users see the test run time or not?

**Comment by bateman** [comment]
No
